-- ============================================================================
-- Nahu Platform
-- Migration : 003_identity_credentials.sql
-- Module    : Identity
-- Author    : Tesfayesus Yimenu Yirdaw
-- Description:
--     Stores authentication credentials for platform users.
-- ============================================================================

BEGIN;

CREATE TABLE identity.credentials
(
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

    user_id UUID NOT NULL UNIQUE,

    password_hash TEXT NOT NULL,

    password_changed_at TIMESTAMPTZ,

    last_login_at TIMESTAMPTZ,

    failed_login_attempts SMALLINT NOT NULL DEFAULT 0,

    locked_until TIMESTAMPTZ,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT fk_credentials_user
        FOREIGN KEY (user_id)
        REFERENCES identity.users(id)
        ON DELETE CASCADE
);

COMMENT ON TABLE identity.credentials IS
'Stores authentication credentials for users. Passwords are stored only as secure hashes.';

COMMENT ON COLUMN identity.credentials.password_hash IS
'Secure password hash generated by the authentication service.';

COMMENT ON COLUMN identity.credentials.failed_login_attempts IS
'Number of consecutive failed login attempts.';

COMMENT ON COLUMN identity.credentials.locked_until IS
'Account remains locked until this timestamp.';

COMMIT;