-- ============================================================================
-- Nahu Platform
-- Migration : 010_identity_relax_registration_constraints.sql
-- Module    : Identity
-- Author    : Package 002 (Identity & Auth)
-- Description:
--     Adjusts two NOT NULL constraints from the original Identity schema so
--     it fits a phone-first, progressive registration flow.
--
--     Context: the existing nahu-buna-gebaya app registers users with just
--     a phone number and a role, verified by SMS OTP -- no password, no
--     name, collected at registration time. Names and passwords (if ever
--     needed) come later, once the user completes their profile.
--
--     Two columns as originally defined don't fit that flow:
--       - identity.credentials.password_hash was NOT NULL, but phone+OTP
--         accounts never set a password.
--       - identity.users.first_name / middle_name were NOT NULL, but a
--         freshly-registered phone-only account has no name yet.
--
--     This migration relaxes both. Applications should still enforce
--     "profile complete" checks in business logic wherever a name is
--     actually required (e.g. before allowing a farmer to publish a
--     listing), rather than at the database level.
-- ============================================================================

BEGIN;

ALTER TABLE identity.credentials
    ALTER COLUMN password_hash DROP NOT NULL;

ALTER TABLE identity.users
    ALTER COLUMN first_name DROP NOT NULL,
    ALTER COLUMN middle_name DROP NOT NULL;

COMMENT ON COLUMN identity.credentials.password_hash IS
'Secure password hash generated by the authentication service. NULL for accounts that authenticate by phone + OTP only and have never set a password.';

COMMENT ON COLUMN identity.users.first_name IS
'Given name. NULL until the user completes their profile -- phone-first registration does not collect this up front.';

COMMENT ON COLUMN identity.users.middle_name IS
'Middle / father''s name. NULL until the user completes their profile.';

COMMIT;
